--------------------------------------------------------------------------------
-- 2016-12-08 13:02:41 - FxGql log file opened
-- 2016-12-08 13:02:41 - FxGql log file closed
--------------------------------------------------------------------------------
-- 2016-12-08 13:04:22 - FxGql log file opened
-- 2016-12-08 13:04:22 - FxGql log file closed
--------------------------------------------------------------------------------
-- 2016-12-08 13:07:00 - FxGql log file opened
-- 2016-12-08 13:07:00 - FxGql log file closed
--------------------------------------------------------------------------------
-- 2016-12-08 13:07:42 - FxGql log file opened
-- 2016-12-08 13:07:42 - FxGql log file closed
--------------------------------------------------------------------------------
-- 2016-12-08 13:23:28 - FxGql log file opened
-- 2016-12-08 13:23:28 - FxGql log file closed
--------------------------------------------------------------------------------
-- 2016-12-08 13:27:26 - FxGql log file opened
-- 2016-12-08 13:27:26 - FxGql log file closed
--------------------------------------------------------------------------------
-- 2016-12-08 13:30:02 - FxGql log file opened
-- 2016-12-08 13:30:02 - FxGql log file closed
