
language: c

os: linux

before_install:
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0E1FAD0C
- sudo apt-get update -qq
- sudo apt-get install mono-complete -qq -y
- sudo mono --version
- mozroots --import --sync --quiet

script:
 - xbuild /p:TargetFrameworkProfile="" /p:Configuration=Release ./FxGql/FxGql.sln
 - ./FxGql/BuildScript/test.sh
