
// This file has been generated by the GUI designer. Do not modify.
namespace FxGqlW
{
	public partial class GqlConsoleWidget
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget FxGqlW.GqlConsoleWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "FxGqlW.GqlConsoleWidget";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
