
// This file has been generated by the GUI designer. Do not modify.
namespace FxGqlW
{
	public partial class ConsoleWidget
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget FxGqlW.ConsoleWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "FxGqlW.ConsoleWidget";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
